FROM node:18.20.4
# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

RUN npx prisma generate
# Expose the application port
EXPOSE 5000

# Start the application
CMD ["node", "dist/index.js"]